default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow inline HTML
MD033: false

# Allow duplicate headings in different sections
MD024:
  siblings_only: true

# Allow trailing punctuation in headings (for Korean)
MD026:
  punctuation: '.,;:!'
